"""Migrate to simpler model for mvp.

Revision ID: a5397ba4e7e2
Revises: b5d567f798c8
Create Date: 2023-08-18 22:24:34.863964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5397ba4e7e2'
down_revision: Union[str, None] = 'b5d567f798c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author_genre_association')
    op.drop_table('preferred_authors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferred_authors',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('author_genre_association',
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('genre_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], )
    )
    # ### end Alembic commands ###
